### ISSUE TITLE
I/O update (runafluid_switch, runaway_rates)

### ISSUE THREAD

**Issue by matyasaradi** [gergopokol/Runafluid#18]
The following input is not used (in EU-IM and in the future in IMAS): `int runafluid_switch`
The following output is not used: `temporary runaway_rates`
The following input is needed (in IMAS): _code parameters_

**Comment by olaszsoma** [comment]
In ITM the unused input parameters have been removed (see [this](https://github.com/osrep/Runafluid/commit/0f9673c67ae1e1210affad40c4f6415331d0cb0b) and [this](https://github.com/osrep/Runafluid/commit/cb6155f635ebc97bc4f386fc8cf0b1321a61e2a8) commit). The issue is still present in IMAS environment.

**Comment by olaszsoma** [comment]
This issue is connected to issue #21, and will be handled there.
