### ISSUE TITLE
Kepler crashes

### ISSUE THREAD

**Issue by pordaniel01** [gergopokol/Runafluid#89]
Kepler crashed when tried to run Runafluid actor on imas.

**Comment by olaszsoma** [comment]
The crash is caused by the missing electric field values in the input IDS data. A check should be implemented which prevents this, similar to the [CPO version](https://github.com/osrep/Runafluid/blob/master/cpo_utils.cpp#L181) and the solution implemented in [Runaway Indicator](https://github.com/osrep/Runin/blob/master/src/ids_utils.cpp#L109).

**Comment by pordaniel01** [comment]
If gcov report is created fc2k fails to generate a Kepler actor. This needs to be addressed.

**Comment by pordaniel01** [comment]
Issues fixed.
